### ISSUE TITLE
Is this fork of flutter_swiper?

### ISSUE THREAD

**Issue by omidraha** [pzentenoe/flutter_card_swipper#1]
Is this [fork](https://github.com/best-flutter/flutter_swiper) of [flutter_swiper ](https://pub.dev/packages/flutter_swiper)?

**Comment by anchao-lu** [comment]
same question

**Comment by Kimsangwon0509** [comment]
same question

**Comment by SalahAdDin** [comment]
@pzentenoe It seems to be a fork.

**Comment by pzentenoe** [comment]
yes

**Comment by SalahAdDin** [comment]
Here, there is another one: https://github.com/TheAnkurPanchani/flutter_swiper. But both this one and the other one has problems with null safety and layout.
